run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gocyclo
    - gocritic
    - nakedret
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  nakedret:
    max-func-lines: 30

issues:
  exclude-use-default: false
